name: Training and Evaluate MNIST Model

on:
  push:
    branches: [main]

jobs:
  train-and-evaluate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Train the Model
      run: python src/train.py

    - name: Evaluate the Model
      run: python src/evaluate.py

    - name: Upload Metrics
      uses: actions/upload-artifact@v3
      with: 
        name: evaluation-results
        path: metrics.json
