name: Training and Evaluate MNIST Model

on:
  push:
    branches: [main]

jobs:
  train-and-evaluate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Train the Model
      run: python source/train.py --model_dir=./saved_model/

    - name: Upload the Model
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: saved_model/

    - name: Evaluate the Model
      run: python source/evaluate.py

    - name: Upload Metrics
      uses: actions/upload-artifact@v4
      with: 
        name: evaluation-results
        path: metrics.json
